title: Notendurchschnitt
question: |
  In der letzten Mathematikarbeit sind folgende Ergebnisse erreicht worden:
  
  | Note | Anzahl Arbeiten |
  |------|-----------------|
  | 1    | 3               |
  | 2    | 10              |
  | 3    | 8               |
  | 4    | 2               |
  | 5    | 2               |
  | 6    | 1               |
solution: |
  $$
  \\bar{x} =
  \\frac{3\\cdot 1+10\\cdot 2+8\\cdot 3+2\\cdot 4+2\\cdot 5+1\\cdot 6}{3+10+8+2+2+1} =
  \\frac{3+20+24+8+10+6}{26} =
  \\frac{71}{26} =4,4375
  $$
